### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by lumauser** [dacoder101/HierarchyCreator#2]
I'm pretty sure that this program also works for macOS since the code you wrote works for Unix based os. Unix based OS being Mac OS and Linux. Change it so that it says that it supports Mac too. Also if you change some part of the code, the python file will still can be ran in windows if you change the OS module code. Maybe we could make a windows version of this.

**Comment by dacoder101** [comment]
Hi! When I was using PyInstaller to create the release (which I will be doing again tomorrow because of a bug), all I needed to change was from "clear" to "cls", which I will edit in the readme. Thanks for letting me know about macOS and Unix!
