### ISSUE TITLE
I GOT THE ROBLOX NOW.GG ON CHROMEBOOK

### ISSUE THREAD

**Issue by lumauser** [dacoder101/HierarchyCreator#3]
Im sorry that I had to tell you this in a github issue but that was the only way i could tell you. I GOT ROBLOX NOW.GG ON CHROMEBOOK RESPOND THEN I WILL TELL YOU

**Comment by lumauser** [comment]
I'll tell you at school since this top secret

**Comment by dacoder101** [comment]
Gotcha :)
