### ISSUE TITLE
Stuck on create new hierarchy after I made one that already has the same name.

### ISSUE THREAD

**Issue by lumauser** [dacoder101/HierarchyCreator#5]
So if I make a hierarchy that has the same name already made, it shows me an error that I can't make another hierarchy that has the same name as an already existing one. But after that, it just comes back the create a new one instead of having a choice of exiting. Maybe when the user inputs exit, you can tell them if they want to close the create new or name a hierarchy "exit".

**Comment by dacoder101** [comment]
Sorry for the late reply. This will be fixed for final release.

**Comment by dacoder101** [comment]
Fixed along with some other bugs.
